backend:
  name: git-gateway
  branch: master

media_folder: posts/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Post'
    folder: 'posts'
    create: true
    slug: 'index'
    media_folder: img
    public_folder: /img
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Feature', name: 'feature', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
